-- =============================================================================
-- El Tradicional · Supabase schema (settings, orders, chat, RLS, RPCs, realtime)
--
-- Setup, once per project:
--   1. Authentication → Sign In / Providers → turn on "Allow anonymous sign-ins"
--      (customers get a device-bound identity without a password).
--   2. SQL editor → run this whole file. It is safe to re-run.
--   3. Authentication → Users → "Add user" for the owner (email + password), then:
--        insert into public.owners (user_id)
--        select id from auth.users where email = 'CORREO-DEL-DUENO';
--   4. In the app, set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY (publishable key) and rebuild.
--
-- Security model: customers and the owner can READ what row-level security allows,
-- but every WRITE except owner settings goes through the security-definer functions below.
-- Known limit: dish prices and barrio fees are still computed in the app; the owner sees
-- them on every order before accepting it.
-- =============================================================================

-- ---------------------------------------------------------------- settings --
create table if not exists public.settings (
  id             smallint primary key default 1 check (id = 1),
  store_open     boolean not null default true,
  plato_dia      text check (plato_dia in ('lunes','martes','miercoles','jueves','viernes','sabado','domingo')),
  day_off        jsonb not null default '{}'::jsonb,
  sold_proteins  jsonb not null default '{}'::jsonb,
  sold_dishes    jsonb not null default '{}'::jsonb,
  juices         jsonb not null default '[{"id":"guandolo","label":"Guandolo","out":false},{"id":"jugo","label":"Jugo","out":false}]'::jsonb,
  promos         jsonb not null default '[{"id":"primer","title":"-20% en tu primer pedido","sub":"Se aplica automáticamente en tu primera compra por la app.","active":true},{"id":"diez","title":"-20% al completar 10 pedidos","sub":"Completa 10 pedidos y el siguiente va con -20%.","active":true}]'::jsonb,
  desc_overrides jsonb not null default '{}'::jsonb,
  updated_at     timestamptz not null default now()
);
insert into public.settings (id) values (1) on conflict (id) do nothing;

create or replace function public.touch_updated_at() returns trigger
language plpgsql set search_path = '' as $$
begin new.updated_at := now(); return new; end $$;

drop trigger if exists settings_touch on public.settings;
create trigger settings_touch before update on public.settings
  for each row execute function public.touch_updated_at();

-- ------------------------------------------------------------------ owners --
create table if not exists public.owners (
  user_id uuid primary key references auth.users (id) on delete cascade
);

create or replace function public.is_owner() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.owners where user_id = (select auth.uid()));
$$;

-- ------------------------------------------------------------------ orders --
create table if not exists public.orders (
  num            bigint generated by default as identity (start with 1043) primary key,
  customer_id    uuid not null,
  name           text not null check (char_length(name) between 1 and 150),
  email          text not null check (char_length(email) between 3 and 200),
  phone          text not null default '—' check (char_length(phone) <= 40),
  origin         text not null check (origin in ('domicilio','recoger')),
  zone_id        text,
  zone_label     text,
  address        text not null default '' check (char_length(address) <= 300),
  address_notes  text not null default '' check (char_length(address_notes) <= 300),
  items          text not null check (char_length(items) <= 4000),
  items_list     jsonb not null default '[]'::jsonb,
  lines          jsonb not null default '[]'::jsonb,
  subtotal       integer not null check (subtotal >= 0),
  discount       integer not null default 0 check (discount >= 0),
  discount_kind  text check (discount_kind in ('primer','diez')),
  delivery       integer not null default 0 check (delivery >= 0),
  total          integer not null check (total >= 0),
  pay            text not null check (char_length(pay) <= 80),
  status         text not null default 'nuevo' check (status in ('nuevo','aceptado','camino','listo','rechazado')),
  reject_reason  text check (char_length(reject_reason) <= 200),
  rated          boolean not null default false,
  review_stars   smallint check (review_stars between 1 and 5),
  review_comment text check (char_length(review_comment) <= 500),
  client_seen_id bigint not null default 0,
  owner_seen_id  bigint not null default 0,
  created_at     timestamptz not null default now()
);
create index if not exists orders_customer_idx on public.orders (customer_id);
create index if not exists orders_email_idx on public.orders (lower(email));
create index if not exists orders_created_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status);

create table if not exists public.order_messages (
  id         bigint generated always as identity primary key,
  order_num  bigint not null references public.orders (num) on delete cascade,
  sender     text not null check (sender in ('cliente','dueno')),
  body       text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);
create index if not exists order_messages_order_idx on public.order_messages (order_num, id);

-- --------------------------------------------------------------------- RLS --
alter table public.settings       enable row level security;
alter table public.owners         enable row level security;
alter table public.orders         enable row level security;
alter table public.order_messages enable row level security;

drop policy if exists settings_read on public.settings;
create policy settings_read on public.settings for select to anon, authenticated using (true);
drop policy if exists settings_owner_update on public.settings;
create policy settings_owner_update on public.settings for update to authenticated
  using ((select public.is_owner())) with check ((select public.is_owner()));

drop policy if exists orders_read on public.orders;
create policy orders_read on public.orders for select to authenticated
  using (customer_id = (select auth.uid()) or (select public.is_owner()));

drop policy if exists order_messages_read on public.order_messages;
create policy order_messages_read on public.order_messages for select to authenticated
  using (
    (select public.is_owner())
    or exists (select 1 from public.orders o where o.num = order_num and o.customer_id = (select auth.uid()))
  );

-- Defense in depth: no direct writes besides the owner's settings update.
revoke all on public.owners from anon, authenticated;
revoke insert, update, delete, truncate on public.orders, public.order_messages from anon, authenticated;
revoke insert, delete, truncate on public.settings from anon, authenticated;
revoke update on public.settings from anon;

-- --------------------------------------------------------------- helpers --
create or replace function public._next_status(p_status text) returns text
language sql immutable set search_path = '' as $$
  select case p_status when 'nuevo' then 'aceptado' when 'aceptado' then 'camino' when 'camino' then 'listo' end;
$$;

create or replace function public._status_note(p_status text, p_origin text) returns text
language sql immutable set search_path = '' as $$
  select case
    when p_status = 'aceptado' then 'Pedido confirmado. Comenzamos con la preparación. 👨‍🍳'
    when p_status = 'camino' and p_origin = 'recoger' then 'Tu pedido está listo para recoger en el local. 🥡'
    when p_status = 'camino' then 'Tu pedido está en camino. 🛵'
    when p_status = 'listo' then 'Pedido entregado. ¡Buen provecho! 😋'
  end;
$$;

-- Loyalty rule (same as src/domain/loyalty.ts): 20% when this customer's non-rejected
-- orders are a multiple of 10; the welcome one (count = 0) only if the email has no
-- orders from another account.
create or replace function public._eligibility(p_uid uuid, p_email text) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare
  n int;
  used boolean;
  ready boolean;
begin
  select count(*) into n from public.orders where customer_id = p_uid and status <> 'rechazado';
  used := n = 0 and exists (
    select 1 from public.orders
    where lower(email) = lower(trim(coalesce(p_email, ''))) and customer_id <> p_uid and status <> 'rechazado');
  ready := n % 10 = 0 and not used;
  return jsonb_build_object(
    'rate', case when ready then 0.2 else 0 end,
    'kind', case when not ready then null when n = 0 then 'primer' else 'diez' end,
    'count', n);
end $$;

-- -------------------------------------------------------------------- RPCs --
create or replace function public.discount_eligibility(p_email text) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if auth.uid() is null then raise exception 'No autenticado.' using errcode = '28000'; end if;
  return public._eligibility(auth.uid(), p_email);
end $$;

create or replace function public.place_order(p jsonb) returns public.orders
language plpgsql security definer set search_path = '' as $$
declare
  uid uuid := auth.uid();
  s public.settings;
  v_email text := trim(coalesce(p->>'email', ''));
  v_origin text := p->>'origin';
  v_sub int := (p->>'subtotal')::int;
  v_delivery int := case when p->>'origin' = 'domicilio' then coalesce((p->>'delivery')::int, 0) else 0 end;
  elig jsonb;
  v_discount int;
  o public.orders;
  m_id bigint;
begin
  if uid is null then raise exception 'No autenticado.' using errcode = '28000'; end if;
  -- one order at a time per customer, so a benefit can't be used twice concurrently
  perform pg_advisory_xact_lock(hashtextextended(uid::text, 0));

  select * into s from public.settings where id = 1;
  if not s.store_open then raise exception 'La cocina está cerrada en este momento. Atendemos 11:30am – 4pm.'; end if;
  if char_length(trim(coalesce(p->>'name', ''))) = 0 then raise exception 'Falta tu nombre.'; end if;
  if v_email !~ '^[^\s@]+@[^\s@]+\.[^\s@]+$' then raise exception 'Falta un correo válido.'; end if;
  if v_origin is null or v_origin not in ('domicilio', 'recoger') then raise exception 'Modo de entrega inválido.'; end if;
  if jsonb_typeof(p->'items_list') <> 'array' or jsonb_array_length(p->'items_list') = 0 then raise exception 'Tu carrito está vacío.'; end if;
  if jsonb_typeof(p->'lines') <> 'array' then raise exception 'Pedido inválido.'; end if;
  if v_sub is null or v_sub < 0 or v_delivery < 0 then raise exception 'Valores inválidos.'; end if;
  if v_origin = 'domicilio' then
    if coalesce(p->>'zone_id', '') = '' then raise exception 'Selecciona tu barrio.'; end if;
    if char_length(trim(coalesce(p->>'address', ''))) = 0 then raise exception 'Escribe la dirección de entrega.'; end if;
  end if;
  if exists (select 1 from jsonb_array_elements(p->'lines') l where coalesce((s.sold_dishes ->> (l->>'dishId'))::boolean, false)) then
    raise exception 'Uno de los platos se agotó. Quítalo del carrito para continuar.';
  end if;
  if s.plato_dia is null and exists (select 1 from jsonb_array_elements(p->'lines') l where l->>'dishId' = 'dia') then
    raise exception 'El menú del día ya no está disponible. Quítalo del carrito para continuar.';
  end if;

  elig := public._eligibility(uid, v_email);
  v_discount := round(v_sub * (elig->>'rate')::numeric);

  insert into public.orders (customer_id, name, email, phone, origin, zone_id, zone_label, address, address_notes,
                             items, items_list, lines, subtotal, discount, discount_kind, delivery, total, pay)
  values (uid, trim(p->>'name'), v_email, coalesce(nullif(trim(p->>'phone'), ''), '—'), v_origin,
          case when v_origin = 'domicilio' then p->>'zone_id' end,
          case when v_origin = 'domicilio' then p->>'zone_label' end,
          case when v_origin = 'domicilio' then trim(p->>'address') else 'Recoge en el local' end,
          case when v_origin = 'domicilio' then trim(coalesce(p->>'address_notes', '')) else '' end,
          p->>'items', p->'items_list', p->'lines', v_sub, v_discount,
          case when v_discount > 0 then elig->>'kind' end,
          v_delivery, greatest(0, v_sub - v_discount + v_delivery), coalesce(p->>'pay', 'Efectivo (contra entrega)'))
  returning * into o;

  insert into public.order_messages (order_num, sender, body)
  values (o.num, 'dueno', 'Hemos recibido tu pedido. Si necesitas algo, puedes escribirnos por este chat. 🙌')
  returning id into m_id;
  update public.orders set client_seen_id = m_id, owner_seen_id = m_id where num = o.num returning * into o;
  return o;
end $$;

create or replace function public.advance_order(p_num bigint) returns public.orders
language plpgsql security definer set search_path = '' as $$
declare o public.orders; ns text;
begin
  if not public.is_owner() then raise exception 'Solo el dueño puede actualizar pedidos.' using errcode = '42501'; end if;
  select * into o from public.orders where num = p_num for update;
  if not found then raise exception 'Pedido no encontrado.'; end if;
  ns := public._next_status(o.status);
  if ns is null then return o; end if;
  update public.orders set status = ns where num = p_num returning * into o;
  insert into public.order_messages (order_num, sender, body) values (p_num, 'dueno', public._status_note(ns, o.origin));
  return o;
end $$;

create or replace function public.reject_order(p_num bigint, p_reason text) returns public.orders
language plpgsql security definer set search_path = '' as $$
declare o public.orders; r text := coalesce(nullif(left(trim(coalesce(p_reason, '')), 200), ''), 'Sin especificar');
begin
  if not public.is_owner() then raise exception 'Solo el dueño puede rechazar pedidos.' using errcode = '42501'; end if;
  select * into o from public.orders where num = p_num for update;
  if not found then raise exception 'Pedido no encontrado.'; end if;
  if o.status not in ('nuevo', 'aceptado') then raise exception 'Este pedido ya no se puede rechazar.'; end if;
  update public.orders set status = 'rechazado', reject_reason = r where num = p_num returning * into o;
  insert into public.order_messages (order_num, sender, body)
  values (p_num, 'dueno', 'Lamentamos informarte que no pudimos procesar tu pedido: ' || r || '. Acepta nuestras disculpas.');
  return o;
end $$;

create or replace function public.send_message(p_num bigint, p_body text) returns public.order_messages
language plpgsql security definer set search_path = '' as $$
declare m public.order_messages; side text; b text := trim(coalesce(p_body, ''));
begin
  if auth.uid() is null then raise exception 'No autenticado.' using errcode = '28000'; end if;
  if b = '' then raise exception 'Mensaje vacío.'; end if;
  if public.is_owner() then side := 'dueno';
  elsif exists (select 1 from public.orders where num = p_num and customer_id = auth.uid()) then side := 'cliente';
  else raise exception 'Pedido no encontrado.' using errcode = '42501';
  end if;
  insert into public.order_messages (order_num, sender, body) values (p_num, side, left(b, 1000)) returning * into m;
  if side = 'dueno' then update public.orders set owner_seen_id = m.id where num = p_num;
  else update public.orders set client_seen_id = m.id where num = p_num; end if;
  return m;
end $$;

create or replace function public.mark_seen(p_num bigint) returns void
language plpgsql security definer set search_path = '' as $$
declare last_id bigint;
begin
  if auth.uid() is null then raise exception 'No autenticado.' using errcode = '28000'; end if;
  select coalesce(max(id), 0) into last_id from public.order_messages where order_num = p_num;
  if public.is_owner() then
    update public.orders set owner_seen_id = last_id where num = p_num and owner_seen_id < last_id;
  else
    update public.orders set client_seen_id = last_id where num = p_num and customer_id = auth.uid() and client_seen_id < last_id;
  end if;
end $$;

create or replace function public.set_review(p_num bigint, p_stars int default null, p_comment text default null, p_rated boolean default null)
returns public.orders
language plpgsql security definer set search_path = '' as $$
declare o public.orders;
begin
  update public.orders set
    review_stars = case when p_stars is null then review_stars else greatest(1, least(5, p_stars)) end,
    review_comment = case when p_comment is null then review_comment else nullif(left(trim(p_comment), 500), '') end,
    rated = rated or coalesce(p_rated, false)
  where num = p_num and customer_id = auth.uid()
  returning * into o;
  if not found then raise exception 'Pedido no encontrado.' using errcode = '42501'; end if;
  return o;
end $$;

-- Functions are executable by PUBLIC by default; only signed-in users may call the API ones.
revoke execute on function public.is_owner(), public._eligibility(uuid, text), public._next_status(text), public._status_note(text, text),
  public.discount_eligibility(text), public.place_order(jsonb), public.advance_order(bigint), public.reject_order(bigint, text),
  public.send_message(bigint, text), public.mark_seen(bigint), public.set_review(bigint, int, text, boolean), public.touch_updated_at()
  from public, anon;
grant execute on function public.is_owner(), public.discount_eligibility(text), public.place_order(jsonb), public.advance_order(bigint),
  public.reject_order(bigint, text), public.send_message(bigint, text), public.mark_seen(bigint), public.set_review(bigint, int, text, boolean)
  to authenticated;
revoke execute on function public._eligibility(uuid, text) from authenticated;

-- ---------------------------------------------------------------- realtime --
do $$
declare t text;
begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    create publication supabase_realtime;
  end if;
  foreach t in array array['settings', 'orders', 'order_messages'] loop
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = t) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end $$;
